sudo: false
os:
  - linux
language: r
assert: false
r_packages:
 - knitr
 - testthat
 - pander
 - XML
 - assertthat
 - stringi
 - rvest
 - data.table
 - magrittr
 - xml2
 - devtools
 - dplyr
 - survival
 - ggplot2
 - tidyr
 - ggthemes
 - purrr
 - viridis
 - scales
 - survminer
bioc_packages:
 - RTCGA.rnaseq
 - RTCGA.clinical
 - RTCGA.mutations
 - RTCGA.CNV
 - RTCGA.PANCAN12
 - RTCGA.RPPA
 - RTCGA.mRNA
 - RTCGA.miRNASeq
 - RTCGA.methylation
 - Biobase
 - GenomicRanges
 - IRanges
 - S4Vectors
