# Dependencies
markdown:         kramdown
kramdown:
  syntax-highlighter: pygments

# Permalinks
permalink: /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:            RTCGA
tagline:          ''
description:      'R packages with TCGA data'
baseurl: "/RTCGA" # If you are making a gh-pages project blog, this is
                        # the name of your project repo, preceded by a /'
                        # Set it to just "" if you are making a user page.
                        
baseurlknitr:  "/RTCGA/" # This will always be your baseurl plus and extra '/'
                                # at the end.  It's used only when knitr renders
                                # your R Markdown files.
                        
url: "https://rtcga.github.io" # the base hostname & protocol for your site

# set limit on number of post to appear on Home page
homepostlimit: 4

# Disqus comments:
disqus:           true
shortname:        RTCGA

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post

author:
  name:           'Marcin Kosiński'
  url:            marcinkosinski.github.io

github:
  repo:           https://github.com/RTCGA/RTCGA
